/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wuzuy;

import java.text.DecimalFormat;

/**
 *
 * @author ffxtr
 */
public class Bhaskara extends javax.swing.JFrame {

    /**
     * Creates new form Bhaskara
     */
    public Bhaskara() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblErro = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        btnGraf = new javax.swing.JButton();
        btnXis = new javax.swing.JButton();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblDelta = new javax.swing.JLabel();
        lblGrafDelta1 = new javax.swing.JLabel();
        lblGrafDelta2 = new javax.swing.JLabel();
        lblGrafDelta3 = new javax.swing.JLabel();
        lblGrafDelta4 = new javax.swing.JLabel();
        lblXisUm = new javax.swing.JLabel();
        lblXisDois = new javax.swing.JLabel();
        lblX1pt1 = new javax.swing.JLabel();
        lblX1pt2 = new javax.swing.JLabel();
        lblX1pt3 = new javax.swing.JLabel();
        lblX1pt4 = new javax.swing.JLabel();
        lblX2pt1 = new javax.swing.JLabel();
        lblX2pt2 = new javax.swing.JLabel();
        lblX2pt3 = new javax.swing.JLabel();
        lblX2pt4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Bhaskara");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);

        lblErro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblErro.setForeground(new java.awt.Color(255, 0, 0));

        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/formula-de-bhaskara-1.png"))); // NOI18N

        lblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stupid.png"))); // NOI18N

        btnCalc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calculadora5050.png"))); // NOI18N
        btnCalc.setText("Fazer o Calculo");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        btnGraf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGraf.setText("Gráfico do Delta");
        btnGraf.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                btnGrafComponentAdded(evt);
            }
        });
        btnGraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafActionPerformed(evt);
            }
        });

        btnXis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXis.setText("Gráfico do X");
        btnXis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXisActionPerformed(evt);
            }
        });

        txtA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        lblA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblA.setText("Valor de A");

        lblB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblB.setText("Valor de B");

        lblC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC.setText("Valor de C");

        lblDelta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblDelta.setForeground(new java.awt.Color(51, 51, 51));
        lblDelta.setText("Δ = ");

        lblGrafDelta1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblGrafDelta1.setForeground(new java.awt.Color(153, 153, 153));

        lblGrafDelta2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblGrafDelta2.setForeground(new java.awt.Color(153, 153, 153));

        lblGrafDelta3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblGrafDelta3.setForeground(new java.awt.Color(153, 153, 153));

        lblGrafDelta4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblGrafDelta4.setForeground(new java.awt.Color(153, 153, 153));

        lblXisUm.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblXisUm.setForeground(new java.awt.Color(51, 51, 51));
        lblXisUm.setText("X² =");

        lblXisDois.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblXisDois.setForeground(new java.awt.Color(51, 51, 51));
        lblXisDois.setText("X¹ =");

        lblX1pt1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX1pt1.setForeground(new java.awt.Color(153, 153, 153));

        lblX1pt2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX1pt2.setForeground(new java.awt.Color(153, 153, 153));

        lblX1pt3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX1pt3.setForeground(new java.awt.Color(153, 153, 153));

        lblX1pt4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX1pt4.setForeground(new java.awt.Color(153, 153, 153));

        lblX2pt1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX2pt1.setForeground(new java.awt.Color(153, 153, 153));

        lblX2pt2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX2pt2.setForeground(new java.awt.Color(153, 153, 153));

        lblX2pt3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX2pt3.setForeground(new java.awt.Color(153, 153, 153));

        lblX2pt4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblX2pt4.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnXis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGraf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblX1pt1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblX1pt4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblX1pt3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblX1pt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblX2pt4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblX2pt3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblX2pt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblX2pt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblC)
                                    .addComponent(lblB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblXisUm)
                            .addComponent(lblDelta)
                            .addComponent(lblXisDois))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGrafDelta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGrafDelta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGrafDelta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGrafDelta4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(lblImg2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImg1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblA)
                                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDelta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblB)
                                    .addComponent(lblXisDois))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblC)
                                    .addComponent(lblXisUm)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGrafDelta2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGrafDelta1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGrafDelta3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(lblGrafDelta4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImg2))
                .addGap(4, 4, 4)
                .addComponent(lblImg1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalc)
                        .addGap(71, 71, 71)
                        .addComponent(btnGraf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXis))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblX1pt1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX1pt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX1pt3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX1pt4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblX2pt1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX2pt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX2pt3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblX2pt4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:

        //Receber valores
        String TextA = txtA.getText();
        String TextB = txtB.getText();
        String TextC = txtC.getText();

        //Caso os valores sejam verdadeiros:
        if (!TextA.isEmpty() && !TextB.isEmpty() && !TextC.isEmpty()) {

            //receber valores
            int A = Integer.parseInt(txtA.getText());
            int B = Integer.parseInt(txtB.getText());
            int C = Integer.parseInt(txtC.getText());

            //contas por trás da folha
            int b1 = (int) Math.pow(B, 2);
            int aXisC = A * C;
            int acXisQuatro = aXisC * -4;
            int Delta = b1 + acXisQuatro;

            lblDelta.setText("Δ = " + Integer.toString(Delta));
        } else { //caso contrário
            lblErro.setText("Por favor, preencha as células vazias!");
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafActionPerformed
        // TODO add your handling code here:
        String TextA = txtA.getText();
        String TextB = txtB.getText();
        String TextC = txtC.getText();

        //Caso os valores sejam verdadeiros:
        if (!TextA.isEmpty() && !TextB.isEmpty() && !TextC.isEmpty()) {

            // Receber valores para o Grafico
            int A = Integer.parseInt(txtA.getText());
            int B = Integer.parseInt(txtB.getText());
            int C = Integer.parseInt(txtC.getText());

            // Calculo por trás da folha
            int b1 = (int) Math.pow(B, 2); // B^2
            int aXisC = A * C; // A . C
            int acXisQuatro = aXisC * -4; // (A.C) . -4
            int Delta = b1 + acXisQuatro; // (B^2) -4 . (A . C)

            //Exibir gráfico do Calc. Delta
            if (acXisQuatro > 0) { //caso ac . -4 seja maior que 0, adicionar +

                int number = acXisQuatro;
                String formattedString = String.format("+%d", number);

                lblGrafDelta1.setText("Δ = " + Integer.toString(B) + "² " + "- 4 . " + Integer.toString(A) + " . " + Integer.toString(C));
                lblGrafDelta2.setText("Δ = " + Integer.toString(b1) + " - 4 . " + Integer.toString(aXisC));
                lblGrafDelta3.setText("Δ = " + Integer.toString(b1) + formattedString);
                lblGrafDelta4.setText("Δ = " + Integer.toString(Delta));
            } else {
                lblGrafDelta1.setText("Δ = " + Integer.toString(B) + "² " + "- 4 . " + Integer.toString(A) + " . " + Integer.toString(C));
                lblGrafDelta2.setText("Δ = " + Integer.toString(b1) + " - 4 . " + Integer.toString(aXisC));
                lblGrafDelta3.setText("Δ = " + Integer.toString(b1) + Integer.toString(acXisQuatro));
                lblGrafDelta4.setText("Δ = " + Integer.toString(Delta));

                if (Delta < 0) {
                    lblXisUm.setText("X¹ inexistente");
                    lblXisDois.setText("X² inexistente");
                    lblErro.setText(" ");
                }
            }
        } else {
            lblErro.setText("Preencha as células para o gráfico!");
        }
    }//GEN-LAST:event_btnGrafActionPerformed

    private void btnGrafComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btnGrafComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrafComponentAdded

    private void btnXisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXisActionPerformed
        // TODO add your handling code here:
        String TextA = txtA.getText();
        String TextB = txtB.getText();
        String TextC = txtC.getText();

        //Caso os valores sejam verdadeiros:
        if (!TextA.isEmpty() && !TextB.isEmpty() && !TextC.isEmpty()) {
            // Receber valores para o Grafico
            int A = Integer.parseInt(txtA.getText());
            int B = Integer.parseInt(txtB.getText());
            int C = Integer.parseInt(txtC.getText());

            // Calculo por trás da folha
            int b1 = (int) Math.pow(B, 2); // B^2
            int aXisC = A * C; // A . C
            int acXisQuatro = aXisC * -4; // (A.C) . -4
            int Delta = b1 + acXisQuatro; // (B^2) -4 . (A . C)

            DecimalFormat df = new DecimalFormat("#.##");

            int bInvertido = B * -1;
            int div = B * 2;
            float DeltaRQ = (float) (Math.sqrt(Delta));
            float aNoX = A * 2;
            float Soma1BeDelta = bInvertido + DeltaRQ;
            float Soma2BeDelta = B + DeltaRQ;
            float x1Final = Soma1BeDelta / aNoX;
            float x2Final = Soma2BeDelta / aNoX;

            String DeltaCD = df.format(DeltaRQ);
            String BeDeltaFl1 = df.format(Soma1BeDelta);
            String BeDeltaFl2 = df.format(Soma2BeDelta);
            String x1FinalFl = df.format(x1Final);
            String x2FinalFl = df.format(x2Final);
            if (Delta < 0) {
                lblX1pt1.setText(" ");
                lblX1pt2.setText(" ");
                lblX1pt3.setText(" ");
                lblX1pt4.setText(" ");
                lblX2pt1.setText(" ");
                lblX2pt2.setText(" ");
                lblX2pt3.setText(" ");
                lblX2pt4.setText(" ");
                lblErro.setText("O Delta é menor que 0, logo, sem raiz!");
                lblXisUm.setText("X¹ inexistente");
                lblXisDois.setText("X² inexistente");

            } else {
                lblX1pt1.setText("x¹ = (-)" + B + " √" + Delta + " / " + "2 . " + A);
                lblX1pt2.setText("x¹ = " + bInvertido + " + " + DeltaCD + " / " + aNoX);
                lblX1pt3.setText("x¹ = " + BeDeltaFl1 + " / " + aNoX);
                lblX1pt4.setText("x¹ = " + x1FinalFl);
                lblXisUm.setText("x¹ = " + x1FinalFl);

                lblX2pt1.setText("x² = (-)" + B + " √" + Delta + " / " + "2 . " + A);
                lblX2pt2.setText("x² = " + B + " + " + DeltaCD + " / " + aNoX);
                lblX2pt3.setText("x² = " + BeDeltaFl2 + " / " + aNoX);
                lblX2pt4.setText("x² = " + x2FinalFl);
                lblXisDois.setText("x² = " + x2FinalFl);
            }
        } else {
            lblErro.setText("Preencha as células para o gráfico!");
        }

//lblXisUm.setText(Integer.toString(bInvertido));
//Teste de verificação

    }//GEN-LAST:event_btnXisActionPerformed

    /**
     * D
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bhaskara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bhaskara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnGraf;
    private javax.swing.JButton btnXis;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblDelta;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblGrafDelta1;
    private javax.swing.JLabel lblGrafDelta2;
    private javax.swing.JLabel lblGrafDelta3;
    private javax.swing.JLabel lblGrafDelta4;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblX1pt1;
    private javax.swing.JLabel lblX1pt2;
    private javax.swing.JLabel lblX1pt3;
    private javax.swing.JLabel lblX1pt4;
    private javax.swing.JLabel lblX2pt1;
    private javax.swing.JLabel lblX2pt2;
    private javax.swing.JLabel lblX2pt3;
    private javax.swing.JLabel lblX2pt4;
    private javax.swing.JLabel lblXisDois;
    private javax.swing.JLabel lblXisUm;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
